export enum PaymentMethod {
  SBERBANK_CREDIT = 'sberbank_credit',
  ALFA_CLICK = 'alfa_click',
  PHONE_BALANCE = 'phone_balance',
  BANK_CARD = 'bank_card',
  PAY_IN_INSTALLMENTS = 'pay_in_installments',
  CASH = 'cash',
  PAY_PARTS = 'pay_parts',
  SPB = 'spb',
  SBERBANK_BUSINESS_ONLINE = 'sberbank_business_online',
  ELECTRONIC_CERTIFICATE = 'electronic_certificate',
  YOOMONEY = 'yoomoney',
  APPLE_PAY = 'apple_pay',
  GOOGLE_PAY = 'google_pay',
  QIWI_WALLET = 'qiwi_wallet',
  SBERPAY = 'sberpay',
  T_PAY = 't_pay',
  WECHAT = 'wechat',
  WEBMONEY = 'webmoney',
}
